### ISSUE TITLE
Issue with forecast_with_covariates method causing ValueError: math domain error

### ISSUE THREAD

**Issue by androidwoman** [google-research/timesfm#113]
Hello,

I encountered an issue with the forecast_with_covariates method in the timesfm library while trying to predict stock prices using dynamic numerical covariates. Below is the detailed description of the problem, along with the code and error message.
 code:
```
import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['JAX_PMAP_USE_TENSORSTORE'] = 'false'
import timesfm
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Load TimesFM model
timesfm_backend = "gpu"  # or 'cpu'
from jax._src import config
config.update("jax_platforms", {"cpu": "cpu", "gpu": "cuda", "tpu": ""}[timesfm_backend])

model = timesfm.TimesFm(
    context_len=512,
    horizon_len=1,
    input_patch_len=32,
    output_patch_len=128,
    num_layers=20,
    model_dims=1280,
    backend=timesfm_backend,
)
model.load_from_checkpoint(repo_id="google/timesfm-1.0-200m")

# Fetch historical data for Apple
ticker = 'AAPL'
data = yf.download(ticker, start="2020-01-01", end="2024-01-01")
data = data[['Close', 'Low', 'High', 'Volume']]
data.reset_index(inplace=True)
data.rename(columns={'Date': 'ds', 'Close': 'y'}, inplace=True)
data['unique_id'] = 'AAPL'
data = data.dropna()

# Prediction
start_date = '2023-01-01'
end_date = '2023-12-31'
window_size = 30

results = []
date_range = pd.date_range(start=start_date, end=end_date)

for i in range(len(date_range) - window_size):
    train_window_start = date_range[i]
    train_window_end = date_range[i + window_size - 1]
    predict_date = date_range[i + window_size]
    train_data = data[(data['ds'] >= train_window_start) & (data['ds'] <= train_window_end)]
    
    if predict_date not in data['ds'].values:
        continue

    try:
        forecasts = model.forecast_with_covariates(
            inputs=[train_data['y'].values],
            dynamic_numerical_covariates={
                'Low': [train_data['Low'].values],
                'High': [train_data['High'].values],
                'Volume': [train_data['Volume'].values],
            },
            static_categorical_covariates={
                'ticker': ['AAPL'] * len(train_data)
            },
            freq=[0] * len(train_data['y']),
            forecast_context_len=window_size,
        )

        result = {
            'ds': predict_date,
            'y_actual': data[data['ds'] == predict_date]['y'].values[0],
            'y_predicted': forecasts[0][0],
            'timesfm-q-0.1': forecasts[1][0][0],
            'timesfm-q-0.2': forecasts[1][0][1],
            'timesfm-q-0.3': forecasts[1][0][2],
            'timesfm-q-0.4': forecasts[1][0][3],
            'timesfm-q-0.5': forecasts[1][0][4],
            'timesfm-q-0.6': forecasts[1][0][5],
            'timesfm-q-0.7': forecasts[1][0][6],
            'timesfm-q-0.8': forecasts[1][0][7],
            'timesfm-q-0.9': forecasts[1][0][8],
        }

        results.append(result)
    except Exception as e:
        print(f"Error in prediction for {predict_date}: {e}")
        continue

results_df = pd.DataFrame(results)
print(results_df)
```

error
```
ValueError: math domain error
Traceback (most recent call last):
    ...
ValueError: math domain error
```

**Comment by siriuz42** [comment]
Likely because the dynamic covariates you provide to the function call are not available for the forecasting horizon. The current implementation does not support past-only dynamic covariates.

There are two hacky ways in the notebook to address this limitation. Please take another look.

**Comment by LOGII33** [comment]
@siriuz42 IM too facing the same problem i cant able to predict close prices which i was just trying to predict with the open, low,high,volume. I got the same error.

class TimesFMCovariatesForecaster:
    """
    TimesFM Forecaster with Covariates Support
    """
    
    def __init__(self, context_len=1024, horizon_len=24, train_split=0.96):
        """
        Initialize TimesFM Covariates Forecaster
        
        Args:
            context_len: Context length for the model
            horizon_len: Forecast horizon length  
            train_split: Fraction of data to use for training
        """
        self.context_len = context_len
        self.horizon_len = horizon_len
        self.train_split = train_split
        self.model = None
        self.df = None
        self.split_idx = None
        self.forecast_results = {}
        
    def setup_model(self):
        """Setup TimesFM model"""
        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Setting up TimesFM model on {device}...")
        
        self.model = timesfm.TimesFm(
            hparams=timesfm.TimesFmHparams(
                backend='gpu',
                context_len=self.context_len,
                per_core_batch_size=32,
                horizon_len=self.horizon_len,
                input_patch_len=32,
                output_patch_len=128,
                num_layers=50,
                model_dims=1280,
                use_positional_embedding=False,
            ),
            checkpoint=timesfm.TimesFmCheckpoint(
                huggingface_repo_id="google/timesfm-2.0-500m-pytorch"
            ),
        )
        print("Model setup complete!")
        
    def prepare_data(self, df, target_col='Close', date_col='Date', 
                    covariate_cols=['Open', 'High', 'Low', 'Volume']):
        """
        Prepare data for forecasting
        
        Args:
            df: Input DataFrame
            target_col: Target variable column name
            date_col: Date column name
            covariate_cols: List of covariate column names
        """
        print("Preparing data...")
        self.df = df.copy()
        self.target_col = target_col
        self.date_col = date_col
        self.covariate_cols = covariate_cols
        
        # Convert date column
        self.df[date_col] = pd.to_datetime(self.df[date_col])
        self.df = self.df.sort_values(date_col).reset_index(drop=True)
        
        # Calculate split index
        if self.horizon_len is None:
            self.split_idx = int(len(self.df) * self.train_split)
            self.horizon_len = len(self.df) - self.split_idx
        else:
            self.split_idx = len(self.df) - self.horizon_len
            
        print(f"Data shape: {self.df.shape}")
        print(f"Split index: {self.split_idx}")
        print(f"Training data: {self.split_idx} points")
        print(f"Test data: {self.horizon_len} points")
        print(f"Target column: {target_col}")
        print(f"Covariate columns: {covariate_cols}")
        
    def create_covariates(self):
        """Create covariate dictionaries for TimesFM"""
        print("Creating covariates...")
        
        # Inputs (target variable context)
        self.inputs = [self.df[self.target_col].iloc[:self.split_idx].tolist()]
        
        # Dynamic numerical covariates (full series including future values)
        self.dynamic_numerical_covariates = {}
        for col in self.covariate_cols:
            if col in self.df.columns:
                self.dynamic_numerical_covariates[col] = [self.df[col].tolist()]
        
        # True values for evaluation
        self.y_true = self.df[self.target_col].iloc[self.split_idx:].tolist()
        
        print(f"Inputs shape: {len(self.inputs[0])} points")
        print(f"Covariates: {list(self.dynamic_numerical_covariates.keys())}")
        print(f"Test target shape: {len(self.y_true)} points")
        
    def forecast(self, xreg_mode="xreg + timesfm", ridge=0.0):
        """
        Run forecasting with covariates
        
        Args:
            xreg_mode: "xreg + timesfm" or "timesfm + xreg"
            ridge: Ridge penalty for linear model
        """
        if self.model is None:
            self.setup_model()
            
        print("Running forecasting with covariates...")
        
        try:
            # Forecast with covariates
            cov_forecast, ols_forecast = self.model.forecast_with_covariates(  
                inputs=self.inputs,
                dynamic_numerical_covariates=self.dynamic_numerical_covariates,
                freq=[0],  # Daily frequency
                xreg_mode=xreg_mode,
                ridge=ridge,
                normalize_xreg_target_per_input=True
            )
            
            # Also get baseline TimesFM forecast for comparison
            baseline_forecast, _ = self.model.forecast(
                inputs=self.inputs, 
                freq=[0]
            )
            
            # Store results
            self.forecast_results = {
                'cov_forecast': cov_forecast[0] if len(cov_forecast.shape) > 1 else cov_forecast,
                'ols_forecast': ols_forecast[0] if len(ols_forecast.shape) > 1 else ols_forecast,
                'baseline_forecast': baseline_forecast[0, :self.horizon_len],
                'y_true': self.y_true
            }
            
            print("Forecasting completed successfully!")
            return self.forecast_results
            
        except Exception as e:
            print(f"Forecasting failed: {str(e)}")
            return None
# Initialize the forecaster
forecaster = TimesFMCovariatesForecaster(
    context_len=1024,
    horizon_len=None,  # Will calculate based on train_split
    train_split=0.94
)

# Run complete analysis
results = forecaster.run_complete_analysis(
    df=df,
    target_col='Close',
    date_col='Date', 
    covariate_cols=['Open', 'High', 'Low', 'Volume']
)

!!ERROR
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[14], line 2
      1 # Run forecasting with covariates
----> 2 cov_forecast, ols_forecast = tfm.forecast_with_covariates(  
      3     inputs=inputs,
      4     dynamic_numerical_covariates=dynamic_numerical_covariates,
      5     freq=[0, 0, 0, 0],  # Daily frequency
      6     xreg_mode="xreg + timesfm",
      7     ridge=0.0,
      8     force_on_cpu=True,
      9     normalize_xreg_target_per_input=True
     10 )

File ~/miniconda3/envs/trde/lib/python3.10/site-packages/timesfm/timesfm_base.py:603, in TimesFmBase.forecast_with_covariates(self, inputs, dynamic_numerical_covariates, dynamic_categorical_covariates, static_numerical_covariates, static_categorical_covariates, freq, window_size, forecast_context_len, xreg_mode, normalize_xreg_target_per_input, ridge, max_rows_per_col, force_on_cpu)
    601 if normalize_xreg_target_per_input:
    602   targets, per_instance_stats = _normalize(targets)
--> 603 xregs, xregs_on_context, _, _, _ = xreg_lib.BatchedInContextXRegLinear(
    604     targets=targets,
    605     train_lens=train_lens,
    606     test_lens=test_lens,
    607     train_dynamic_numerical_covariates=train_dynamic_numerical_covariates,
    608     test_dynamic_numerical_covariates=test_dynamic_numerical_covariates,
    609     train_dynamic_categorical_covariates=
    610     train_dynamic_categorical_covariates,
    611     test_dynamic_categorical_covariates=
    612     test_dynamic_categorical_covariates,
    613     static_numerical_covariates=static_numerical_covariates,
    614     static_categorical_covariates=static_categorical_covariates,
    615 ).fit(
    616     ridge=ridge,
    617     one_hot_encoder_drop=None if ridge > 0 else "first",
    618     max_rows_per_col=max_rows_per_col,
    619     force_on_cpu=force_on_cpu,
    620     debug_info=True,
    621     assert_covariates=True,
    622     assert_covariate_shapes=True,
    623 )
    624 mean_outputs, _ = self.forecast(
    625     [
    626         target - xreg_on_context
   (...)
    632     return_forecast_on_context=True,
    633 )
    634 outputs = [
    635     (mean_output[self._horizon_start:(self._horizon_start + test_len)] +
    636      xreg)
    637     for mean_output, test_len, xreg in zip(mean_outputs, test_lens, xregs)
    638 ]

File ~/miniconda3/envs/trde/lib/python3.10/site-packages/timesfm/xreg_lib.py:459, in BatchedInContextXRegLinear.fit(self, ridge, one_hot_encoder_drop, use_intercept, force_on_cpu, max_rows_per_col, max_rows_per_col_sample_seed, debug_info, assert_covariates, assert_covariate_shapes)
    457 x_train = _to_padded_jax_array(x_train)
    458 flat_targets = _to_padded_jax_array(flat_targets)
--> 459 x_test = _to_padded_jax_array(x_test)
    460 beta_hat = (jnp.linalg.pinv(
    461     x_train.T @ x_train + ridge * jnp.eye(x_train.shape[1]),
    462     hermitian=True,
    463 ) @ x_train.T @ flat_targets)
    464 y_hat = x_test @ beta_hat

File ~/miniconda3/envs/trde/lib/python3.10/site-packages/timesfm/xreg_lib.py:49, in _to_padded_jax_array(x)
     47 elif x.ndim == 2:
     48   i, j = x.shape
---> 49   di = 2**math.ceil(math.log2(i)) - i
     50   dj = 2**math.ceil(math.log2(j)) - j
     51   return jnp.pad(x, ((0, di), (0, dj)), mode="constant", constant_values=0.0)

ValueError: math domain error
