### ISSUE TITLE
asyncio error when loading checkpoint

### ISSUE THREAD

**Issue by butterflywaltz** [google-research/timesfm#120]
Has anyone encountered below error when doing `tfm.load_from_checkpoint(repo_id="google/timesfm-1.0-200m")`?  

Installed on Windows WSL, Python 3.10, using `pip install timesfm`  

```
  File "/root/anaconda3/envs/tfm_env/lib/python3.10/site-packages/jax/experimental/array_serialization/serialization.py", line 180, in __init__
    self._cv = asyncio.Condition(lock=asyncio.Lock())
  File "/root/anaconda3/envs/tfm_env/lib/python3.10/asyncio/locks.py", line 234, in __init__
    raise ValueError("loop argument must agree with lock")
ValueError: loop argument must agree with lock
```

**Comment by sandeepnishad6060** [comment]
Try by updating the packages using

pip install --upgrade jax jaxlib

**Comment by Yash1927** [comment]
Try by updating the packages using

1: pip install --upgrade jax jaxlib

2: Initialize the Lock Properly

3: use different version

**Comment by butterflywaltz** [comment]
Thanks. This is a Python issue related to earlier versions of 3.10  
https://bugs.python.org/issue45416  

I did a `conda install python==3.10.14` and it works now.
