### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by MichaelisTrofficus** [google-research/timesfm#14]
Any resources / advises on how to finetune this model on a specific timeseries dataset?

**Comment by hvacking** [comment]
Same question.

**Comment by notnotsamuel** [comment]
Would be interested too.

**Comment by zx377262372** [comment]
+1,same too,thanks

**Comment by ohadmomo** [comment]
+1

**Comment by Tangjiandd** [comment]
Would be interested too.

**Comment by androidwoman** [comment]
Same question

**Comment by projectavi** [comment]
https://github.com/google-research/timesfm/blob/master/notebooks/finetuning.ipynb - they recently added this

**Comment by rajatsen91** [comment]
See an example here. It is meant to familiarize users mainly with paxml finetuning. You can of course bring your own data loader as well.
