### ISSUE TITLE
How to run timesfm on torch, questions and solve plan !

### ISSUE THREAD

**Issue by guiyang882** [google-research/timesfm#143]
https://github.com/google-research/timesfm/blob/16d84e9c43f7af0f8b26c8a17a99518e39050f01/src/timesfm_torch/pytorch_patched_decoder.py#L707

in this code scripts, could you add some comments or examples to display how to make input tensors, about tensor shapes.
i try some input mode, but get some exception.

```
import torch
import numpy as np
from torchviz import make_dot


def make_input_paddings(n_batch, n_context, n_horizon):
    np_zero = np.zeros((n_batch, n_context))
    return np_zero
    # np_ones = np.ones((n_batch, n_horizon))
    # return np.concatenate([np_zero, np_ones], axis=1)


n_batch = 1
n_context = 512
n_horizon = 128
input_ts = np.random.random((n_batch, n_context))
paddings = make_input_paddings(n_batch, n_context, n_horizon)
np_freq = np.zeros((n_batch, 1))

tensor_input_ts = torch.Tensor(input_ts)
tensor_input_padding = torch.LongTensor(paddings)
tensor_freq = torch.LongTensor(np_freq)

print(tensor_input_ts.shape)
print(tensor_input_padding.shape)
print(tensor_freq.shape)

y = tfm_model(
        input_ts=tensor_input_ts,
        input_padding=tensor_input_padding,
        freq=tensor_freq
    )
print(y.shape)
```

I got this error message

```
/timesfm_torch/models.py:293, in StackedDecoder.forward(self, hidden_states, paddings, kv_write_indices, kv_caches)
    [286](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:286) def forward(
    [287](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:287)     self,
    [288](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:288)     hidden_states: torch.Tensor,
   (...)
    [291](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:291)     kv_caches: List[Tuple[torch.Tensor, torch.Tensor]] | None = None,
    [292](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:292) ) -> torch.Tensor:
--> [293](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:293)     padding_mask = convert_paddings_to_mask(paddings, hidden_states.dtype)
    [294](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:294)     atten_mask = causal_mask(hidden_states)
    [295](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/models.py:295)     mask = merge_masks(padding_mask, atten_mask)

File /disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:143, in convert_paddings_to_mask(paddings, dtype)
    [132](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:132) """Converts binary paddings to a logit mask ready to add to attention matrix.
    [133](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:133) 
    [134](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:134) Args:
   (...)
    [140](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:140)     A torch.Tensor of shape [B, 1, 1, T] ready to add to attention logits.
    [141](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:141) """
    [142](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:142) attention_mask = paddings[:, None, None, :]  # Equivalent to jnp.newaxis
--> [143](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:143) attention_mask *= get_large_negative_number(dtype)
    [144](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225055425f485a5f4543535f4750555f7634227d.vscode-resource.vscode-cdn.net/disk01/wuming.lgy.workspace/timesfm_repo/timesfm/src/timesfm_torch/utils.py:144) return attention_mask

RuntimeError: result type Float can't be cast to the desired output type Long
```

**Comment by guiyang882** [comment]
the origin code about convert_paddings_to_mask have some errors.
should fix by this

```
def convert_paddings_to_mask(
        paddings: torch.Tensor, dtype: torch.dtype = torch.float32) -> torch.Tensor:
    """Converts binary paddings to a logit mask ready to add to attention matrix.

    Args:
        paddings: binary torch.Tensor of shape [B, T], with 1 denoting padding
          token.
        dtype: data type of the input.

    Returns:
        A torch.Tensor of shape [B, 1, 1, T] ready to add to attention logits.
    """
    attention_mask = paddings[:, None, None, :].float()  # Equivalent to jnp.newaxis
    attention_mask *= get_large_negative_number(dtype)
    return attention_mask
```

**Comment by guiyang882** [comment]
![image](https://github.com/user-attachments/assets/06b0a2de-b554-4114-81a1-83cefcc604ae)

I analyzed the model names provided by the official PyTorch version and the JAX version, and I found that there are still some differences in the names. Could the official team provide a script for converting a JAX checkpoint to a PyTorch checkpoint?

**Comment by guiyang882** [comment]
![image](https://github.com/user-attachments/assets/2279dc28-85c2-4412-acce-ec738eb96588)

I noticed that the weight structure provided by the official PyTorch version of the transform is inconsistent with the weight structure of JAX during the weight conversion process. Is there any way to resolve this?

**Comment by guiyang882** [comment]
@rajatsen91 Can you help me look into this issue? 🙏

**Comment by guiyang882** [comment]
> ![image](https://private-user-images.githubusercontent.com/5275638/366775763-2279dc28-85c2-4412-acce-ec738eb96588.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzI3OTIsIm5iZiI6MTcyNjEzMjQ5MiwicGF0aCI6Ii81Mjc1NjM4LzM2Njc3NTc2My0yMjc5ZGMyOC04NWMyLTQ0MTItYWNjZS1lYzczOGViOTY1ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDkxNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NkNWVhZjUyMDc5MWEwYWJlMWY2NWJlNmZjZGQzZWE5YmViMzc1ZjY0ZmQxZmEyMzVmYmM0M2JhY2YwZTJkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2YYhgYPRosHhmH26JP7PdUCs5w_l1w6yQKJloNXN_dI)
> 
> I noticed that the weight structure provided by the official PyTorch version of the transform is inconsistent with the weight structure of JAX during the weight conversion process. Is there any way to resolve this?


I look forward you code, that may be the answer.

```
        self.qkv_proj = nn.Linear(
            self.hidden_size,
            (self.num_heads + 2 * self.num_kv_heads) * self.head_dim,
        )
        self.o_proj = nn.Linear(
            self.num_heads * self.head_dim, self.hidden_size)
```
i guess reshape the jax tensor into 2-dims , then concat (q, k, v) weights into one tensor
the same operation with the q, k, v bias ?

**Comment by guiyang882** [comment]
```
def _create_quantiles() -> list[float]:
    return [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
```

in timesfm torch version, the `_create_quantiles` should change into `[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]`.
otherwise, jax weights should not match the shape.

**Comment by rajatsen91** [comment]
Hi all,  we will release timesfm_torch.py which will be a wrapper over pytorch_patched_decoder.py and will be easy to use (with isntructions). We will also upload the weights in torch to huggingface. Please stay tuned till the end of this week.

**Comment by guiyang882** [comment]
> Hi all, we will release timesfm_torch.py which will be a wrapper over pytorch_patched_decoder.py and will be easy to use (with isntructions). We will also upload the weights in torch to huggingface. Please stay tuned till the end of this week.

till the end of this week. 😄 Very much looking forward to it.

I would like to use the TimesFM architecture to train for other time series tasks, such as time series anomaly detection tasks. Could you please provide some guidance? 😁

**Comment by guiyang882** [comment]
@rajatsen91 
Another question about torch code process out function
```
    def _postprocess_output(
        self,
        model_output: torch.Tensor,
        num_outputs: int,
        stats: tuple[torch.Tensor, torch.Tensor],
    ) -> torch.Tensor:
        """Postprocess output of stacked transformer."""

        # B x N x (H.Q)
        output_ts = self.horizon_ff_layer(model_output)

        # Reshape using view
        b, n, _ = output_ts.shape
        output_ts = output_ts.view(b, n, self.config.horizon_len, num_outputs)

        return self._reverse_transform(output_ts, stats)
```

```
output_ts = output_ts.view(b, n, self.config.horizon_len, num_outputs)
```
in this code, hidden_size = 1280, that means `horizon_len` must equal 128 ?
we cannot set any value about `horizon_len` .

**Comment by guiyang882** [comment]
@rajatsen91 
the jax model regression effect

```
xs = np.linspace(0, 2048, 512)
ys = np.sin(xs)
frequency_input = [0]
```

![image](https://github.com/user-attachments/assets/0c3b5443-368e-42f1-a406-39de67fb3d5b)

the regression result is here.

the total code here

```
# 加载 jax 权重，然后使用 jax 权重
import numpy as np
import importlib
import sys
import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['JAX_PMAP_USE_TENSORSTORE'] = 'false'

timefm_dir_path = "./timesfm_repo/timesfm/src"

sys.path.insert(0, timefm_dir_path)
importlib.reload(sys)

import timesfm

tfm_jax = timesfm.TimesFm(
    context_len=512,
    horizon_len=128,
    input_patch_len=32,
    output_patch_len=128,
    num_layers=20,
    model_dims=1280,
    backend="cpu",
)
tfm_jax.load_from_checkpoint(
    checkpoint_path="./timesfm_repo/timesfm-1.0-200m/checkpoints")


forecast_input = [
    np.sin(np.linspace(0, 2048, 512)),
]
frequency_input = [0]

point_forecast, experimental_quantile_forecast = tfm_jax.forecast(
    forecast_input,
    freq=frequency_input,
)

print(point_forecast.shape)
print(experimental_quantile_forecast.shape)
```

**Comment by guiyang882** [comment]
![image](https://github.com/user-attachments/assets/28538a9d-bad8-472f-aaf8-72e42dacb372)

@rajatsen91 

torch version release !!!!

**Comment by guiyang882** [comment]
@rajatsen91 hi, i use torch version timesfm model. when i use different input, the series prediction may have different mae value.

```
import numpy as np
from matplotlib import pyplot as plt


forecast_input = [
    np.sin(np.linspace(0, 20, 100)),
    np.sin(np.linspace(0, 20, 200)),
    np.sin(np.linspace(0, 20, 400)),
]
frequency_input = [0, 1, 2]

point_forecast, experimental_quantile_forecast = tfm.forecast(
    forecast_input,
    freq=frequency_input,
)
print(point_forecast.shape)
print(experimental_quantile_forecast.shape)


# 这里针对原始数据和预测数据进行可视化
x = forecast_input[0].reshape((1, -1))

n_size = x.shape[1]
xs = list(range(0, n_size))
ys = x[0, :].tolist()

y_show_hat = experimental_quantile_forecast[0, :, :]
print(y_show_hat.shape)

n_pred_size = y_show_hat.shape[0]
n_show_line = y_show_hat.shape[1]
xs_tmp = list(range(n_size, n_size+n_pred_size))

plt.figure(figsize=(20, 4))
plt.plot(xs, ys)
for i in range(0, n_show_line):
    ys_tmp = y_show_hat[:, i].tolist()
    if i == 0:
        name = "value"
    else:
        name = f"p_0.{i}"
        
    plt.plot(xs_tmp, ys_tmp, label=name, linestyle="--")
plt.legend()

plt.show()

```

![image](https://github.com/user-attachments/assets/0298aa68-5723-4bd4-9239-d1a6ed65ed95)


```
forecast_input = [
    np.sin(np.linspace(0, 100, 100)),
    np.sin(np.linspace(0, 20, 200)),
    np.sin(np.linspace(0, 20, 400)),
]
```

![image](https://github.com/user-attachments/assets/74cb58a7-2a30-4692-95e8-d83956faf0ba)

```
forecast_input = [
    np.sin(np.linspace(0, 200, 100)),
    np.sin(np.linspace(0, 20, 200)),
    np.sin(np.linspace(0, 20, 400)),
]
```

![image](https://github.com/user-attachments/assets/e7895f6f-db30-41aa-8f49-9935004ad382)

**Comment by guiyang882** [comment]
hi，I read the torch code scripts carefully. One Question about that.

```
    def _preprocess(self, inputs: Sequence[np.array],
                    freq: Sequence[int]) -> tuple[np.array, np.array, int]:
        """Formats and pads raw inputs to feed into the model.

        This function both pads each time series to match the context length, and
        pads the inputs to meet the SPMD shape requirement.

        Args:
          inputs: A list of 1d JTensors. Each JTensor is the context time series of
            a single forecast task.
          freq: list of frequencies

        Returns:
        A tuple of:
        - the padded input time series to meet the model required context.
        - the padding indicator.
        - the number of padded examples for SPMD so that each core has the same
            number (a multiple of `batch_size`) of examples.
        """

        input_ts, input_padding, inp_freq = [], [], []

        pmap_pad = ((len(inputs) - 1) // self.global_batch_size +
                    1) * self.global_batch_size - len(inputs)
```

`pmap_pad` why you should calculate this value ?
In the PyTorch version of the code, how is the SPMD operation reflected ?

@rajatsen91

**Comment by rajatsen91** [comment]
> hi，I read the torch code scripts carefully. One Question about that.
> 
> ```
>     def _preprocess(self, inputs: Sequence[np.array],
>                     freq: Sequence[int]) -> tuple[np.array, np.array, int]:
>         """Formats and pads raw inputs to feed into the model.
> 
>         This function both pads each time series to match the context length, and
>         pads the inputs to meet the SPMD shape requirement.
> 
>         Args:
>           inputs: A list of 1d JTensors. Each JTensor is the context time series of
>             a single forecast task.
>           freq: list of frequencies
> 
>         Returns:
>         A tuple of:
>         - the padded input time series to meet the model required context.
>         - the padding indicator.
>         - the number of padded examples for SPMD so that each core has the same
>             number (a multiple of `batch_size`) of examples.
>         """
> 
>         input_ts, input_padding, inp_freq = [], [], []
> 
>         pmap_pad = ((len(inputs) - 1) // self.global_batch_size +
>                     1) * self.global_batch_size - len(inputs)
> ```
> 
> `pmap_pad` why you should calculate this value ? In the PyTorch version of the code, how is the SPMD operation reflected ?
> 
> @rajatsen91

This is a good question. Technically if we do not compile the torch model then this is not needed. But I believe if we compile the model then keeping the batch size the same using the `pmap_pad` migth have speed benefits. Currently the torch code does not compile the model and also we do not support multi-gpu inference (that will change soon).
