### ISSUE TITLE
Lags in forecasting with TimesFM

### ISSUE THREAD

**Issue by imontoyah** [google-research/timesfm#157]
I've been working with TimesFM, and I was wondering if it's possible to generate a forecast with a lag, without calculating all the intermediate points. Specifically, if I have data points from 1 to 10 and want to forecast points from 15 to 20, can I do so directly? Or is it mandatory to forecast all points from 11 to 20?

If this functionality isn't currently available, are there any plans to implement it?

**Comment by rajatsen91** [comment]
Hi @imontoyah, Currently that is not possible and it is not on our immediate roadmap. It is possible in principle but for that we need to retrain our model with corresponding masking.
