### ISSUE TITLE
Error loading TimesFM

### ISSUE THREAD

**Issue by blackhole-canada** [google-research/timesfm#164]
Hello, I am pretty new to this model and I was trying to do some tests. I was trying to load the model using the following 

`model = timesfm.TimesFm(`
    `context_len=512,`
    `horizon_len=128,`
    `input_patch_len=32,`
    `output_patch_len=128,`
    `num_layers=20,`
    `model_dims=1280,`
    `backend='cpu',`
`)`
`model.load_from_checkpoint(repo_id="google/timesfm-1.0-200m-pytorch")`

TimesFmBase.__init__() got an unexpected keyword argument 'context_len'. I am getting the error for all of the arguments.

I am on Python 3.11 and I have installed the timesfm using pip correctly.

**Comment by rajatsen91** [comment]
We have moved to a different format for loading: https://github.com/google-research/timesfm?tab=readme-ov-file#usage
