### ISSUE TITLE
Calling timesfm.TimesFm().load_from_checkpoint() within asynchronous function

### ISSUE THREAD

**Issue by aleksmaksimovic** [google-research/timesfm#167]
Hello,

I'm working on some project where I want to call and instantiate a TimesFM model within an **asynchronous** function:

```
 async def main(self):

   tfm = timesfm.TimesFm(
                  context_len=512,
                  horizon_len=128,
                  input_patch_len=32,
                  output_patch_len=128,
                  num_layers=20,
                  model_dims=1280,
                  backend="gpu",
              )
              tfm.load_from_checkpoint(repo_id="google/timesfm-1.0-200m")
```

I get the following error:

_RuntimeError: asyncio.run() cannot be called from a running event loop_

The error seems to be thrown as soon as the function tfm.load_from_checkpoint() is called:

venv/lib/python3.10/site-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 171, in get_byte_limiter

As the pytree_checkpoint_handler seems to contain asynchronous code themself, is there any other way to load the model from a checkpoint within an asynchronous function?

**Comment by YuriyTW** [comment]
Hey! Could you please advise how you got around this error?
