### ISSUE TITLE
AttributeError: 'TimesFmJax' object has no attribute '_median_index' in TimesFM forecast function

### ISSUE THREAD

**Issue by StevenChen16** [google-research/timesfm#181]
**Description**:  
I am encountering an `AttributeError` while using the `forecast` function with the `TimesFmJax` model. This error occurs across multiple versions, including `0.1.23`, `0.1.32`, `1.1.0`, and `1.2.2`. The error message is as follows:

```plaintext
AttributeError                            Traceback (most recent call last)
Cell In[19], line 10
      3 forecast_input = [
      4     np.sin(np.linspace(0, 20, 100)),
      5     np.sin(np.linspace(0, 20, 200)),
      6     np.sin(np.linspace(0, 20, 400)),
      7 ]
      8 frequency_input = [0, 1, 2]
---> 10 point_forecast, experimental_quantile_forecast = tfm.forecast(
     11     forecast_input,
     12     freq=frequency_input,
     13 )

File /opt/conda/lib/python3.10/site-packages/timesfm/timesfm_base.py:332, in TimesFmBase.forecast(self, inputs, freq, window_size, forecast_context_len, return_forecast_on_context, normalize)
    330   return mean_forecast, quantile_forecast
    331 elif self.hparams.point_forecast_mode == "median":
--> 332   if self._median_index == -1:
    333     for i, quantile in enumerate(self.quantiles):
    334       if quantile == 0.5:

AttributeError: 'TimesFmJax' object has no attribute '_median_index'
```

**Steps to Reproduce**:  
I am using the official example provided by TimesFM, and the error persists. Here is the code:

```python
import numpy as np

forecast_input = [
    np.sin(np.linspace(0, 20, 100)),
    np.sin(np.linspace(0, 20, 200)),
    np.sin(np.linspace(0, 20, 400)),
]
frequency_input = [0, 1, 2]

point_forecast, experimental_quantile_forecast = tfm.forecast(
    forecast_input,
    freq=frequency_input,
)
```

**Expected Behavior**:  
The `forecast` function should return `point_forecast` and `experimental_quantile_forecast` as expected in the example.

**Actual Behavior**:  
Instead, the following `AttributeError` is raised:
```
AttributeError: 'TimesFmJax' object has no attribute '_median_index'
```

**Additional Information**:  
The error occurs regardless of the TimesFM version I use (`0.1.23`, `0.1.32`, `1.1.0`, or `1.2.2`). I have installed these versions via pip. Is there a specific version or setup required to avoid this issue?

**Comment by rajatsen91** [comment]
It should be fixed now in version 1.2.3
