### ISSUE TITLE
Conflict Between Python 3.11 Requirement for Torch Version and Incompatibility of Lingvo, Praxis, and Paxml

### ISSUE THREAD

**Issue by wangdaozzz** [google-research/timesfm#187]
In your README, it is mentioned that Python 3.11 is required to use the Torch version. However, if Python 3.11 is used, Lingvo, Praxis, and Paxml cannot be installed due to the Python version being too high. How can this issue be resolved?

**Comment by rajatsen91** [comment]
The torch version [here](https://github.com/google-research/timesfm?tab=readme-ov-file#install-from-pypi-and-publish) actually does not need to install Lingvo, Praxis, and Paxml. So it should work without installing these packages as well.

**Comment by wangdaozzz** [comment]
> The torch version [here](https://github.com/google-research/timesfm?tab=readme-ov-file#install-from-pypi-and-publish) actually does not need to install Lingvo, Praxis, and Paxml. So it should work without installing these packages as well.

Thanks for your reply, but I think the finetune model and the ipynd file you provided seem to be based on PAX, so I am a little confused about their relationship.

**Comment by wangdaozzz** [comment]
> The torch version [here](https://github.com/google-research/timesfm?tab=readme-ov-file#install-from-pypi-and-publish) actually does not need to install Lingvo, Praxis, and Paxml. So it should work without installing these packages as well.

I see. After I enter this in poetry install -e torch, the timesfm library is installed in Python, and then the file pytorch_patched_decoder.py will be called. Then you haven't released the tuning file about torch version?

**Comment by Jon-tao** [comment]
@wangdaozzz  have you solved the problem? I met the same. I can not run the finetune model and the ipynb.

**Comment by wangdaozzz** [comment]
> @wangdaozzz 你解决了这个问题吗？我也遇到了同样的问题。我无法运行微调模型和 ipynb。

no，i can t understand the ReadMe

**Comment by Jon-tao** [comment]
@wangdaozzz maybe the notebooks can be played

**Comment by rajatsen91** [comment]
Hi all, it is true that the notebook only shows example of finetuning with the jax model. We have not released the pytorch fientuning code. However since pytorch is widely used we are hoping we can have community contributions in that direction.
