### ISSUE TITLE
COVARIATES: unexpected keyword argument 'context_len'

### ISSUE THREAD

**Issue by ozanbarism** [google-research/timesfm#191]
I run this cell from the covariates.ipynb

timesfm_backend = "cpu"  # @param

from jax._src import config
config.update(
    "jax_platforms", {"cpu": "cpu", "gpu": "cuda", "tpu": ""}[timesfm_backend]
)

model = timesfm.TimesFm(
    context_len=512,
    horizon_len=128,
    input_patch_len=32,
    output_patch_len=128,
    num_layers=20,
    model_dims=1280,
    backend=timesfm_backend,
)
model.load_from_checkpoint(repo_id="google/timesfm-1.0-200m")

It results in this error!

TypeError: TimesFmBase.__init__() got an unexpected keyword argument 'context_len'

**Comment by chenchihwen** [comment]
i have the same issue

**Comment by rajatsen91** [comment]
The interface is now slightly different: https://github.com/google-research/timesfm?tab=readme-ov-file#usage
