### ISSUE TITLE
Support for Custom Loss Functions During Fine-Tuning

### ISSUE THREAD

**Issue by Arsa-Nik** [google-research/timesfm#193]
I'm trying to fine-tune the TimesFM model on intermittent time-series data. The default avg_qloss loss function isn't ideal because quantile predictions vary significantly. I aim to focus the loss computation solely on the median (50th percentile).
When specifying only the median quantile, the model throws a dimension mismatch error since it's pre-trained on multiple quantiles.
```
tfm = timesfm.TimesFm(
    hparams=timesfm.TimesFmHparams(
        backend="gpu",
        per_core_batch_size=16,
        horizon_len=3,
        quantiles=[0.5],  # Attempting to set only the median quantile
    ),
    checkpoint=timesfm.TimesFmCheckpoint(
        huggingface_repo_id="google/timesfm-1.0-200m"
    ),
)
```
Error:
```
ScopeParamShapeError: Initializer expected to generate shape (1280, 1280) but got shape (1280, 256) instead for parameter "w" in "/horizon_ff_layer/output_layer/linear".
```
Is it possible to specify a custom loss function in fine tuning step that targets specific quantiles (e.g., the median) without altering the model's architecture? or alternatively, can the model be configured to ignore certain quantiles during loss computation while retaining the expected parameter shapes in below section?
```
@pax_fiddle.auto_config
def build_learner() -> learners.Learner:
    return pax_fiddle.Config(
        learners.Learner,
        name='learner',
        loss_fn=median_quantile_loss,  # Custom median quantile loss
#       loss_name='qloss',  # or using qloss with specified quantile
#       quantiles = [0.5]
        optimizer=optimizers.Adam(
            epsilon=1e-7,
            clip_threshold=1e2,
            learning_rate=1e-2,
            lr_schedule=pax_fiddle.Config(
                schedules.Cosine,
                initial_value=1e-3,
                final_value=1e-4,
                total_steps=40000,
            ),
            ema_decay=0.9999,
        ),
        bprop_variable_exclusion=['.*/stacked_transformer_layer/.*'],
    )

**Comment by rajatsen91** [comment]
You can locally clone the package and directly modify the loss function here: https://github.com/google-research/timesfm/blob/master/src/timesfm/patched_decoder.py#L528
