### ISSUE TITLE
TypeError: TimesFmBase.__init__() got an unexpected keyword argument 'context_len'

### ISSUE THREAD

**Issue by thks-for-the-help** [google-research/timesfm#195]
```
import pandas as pd
import numpy as np
import timesfm as tf

# Carica il file CSV
df = pd.read_csv("file.csv", parse_dates=["Datetime"])
df = df.set_index("Datetime")

# Configurazione del modello
tfm = tf.TimesFm(
    context_len=128,  # Contesto massimo (modificabile)
    horizon_len=5,    # Orizzonte di previsione
    input_patch_len=32,
    output_patch_len=128,
    num_layers=20,
    model_dims=1280,
    backend="gpu",    # Cambia in "cpu" se necessario
)
```
 I receive back: 

> TypeError: TimesFmBase.__init__() got an unexpected keyword argument 'context_len'

 despite is the standard instruction were officially given . Thanks

**Comment by rajatsen91** [comment]
WE have moved to using TimesFM Hparams. Please see https://github.com/google-research/timesfm?tab=readme-ov-file#usage

**Comment by catsled** [comment]
hparams=timesfm.TimesFmHparams(
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TimesFmHparams.__init__() got an unexpected keyword argument 'use_positional_embedding'

**Comment by l1k3l** [comment]
> hparams=timesfm.TimesFmHparams( ^^^^^^^^^^^^^^^^^^^^^^^ TypeError: TimesFmHparams.**init**() got an unexpected keyword argument 'use_positional_embedding'

I have the same issue🙋🏽‍♂️
