### ISSUE TITLE
Can't access huggingface timesfm-1.0-200m anymore.

### ISSUE THREAD

**Issue by Ellalina** [google-research/timesfm#199]
I'm trying to access the huggingface repto "google/timesfm-1.0-200m" on two different servers, first a private server, where I get the following error message:

ProxyError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: [/api/models/google/timesfm-1.0-200m/revision/main](userURL) (Caused by ProxyError(\'Unable to connect to proxy\', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f79806ed000>: Failed to resolve \userProxy\' ([Errno -3] Temporary failure in name resolution)")))'), '(Request ID: 62df458c-4d89-413f-b923-a117212f95b2)')

Or this one, on both servers, the second one is google colab:
TypeError: TimesFmBase.__init__() got an unexpected keyword argument 'context_len'

for running the pax version of TimesFM, which is needed to fine-tune TimesFM. Is there a reason for that? Or is there another way on how to fine-tune TimesFM with the torch version?

**Comment by rajatsen91** [comment]
Sorry for the breakage but we have updated the initialization of the class: https://github.com/google-research/timesfm?tab=readme-ov-file#initialize-the-model-and-load-a-checkpoint
