### ISSUE TITLE
Is this normal to use 12G GPU memory to load the 200m model with default parameter?

### ISSUE THREAD

**Issue by keefeleen** [google-research/timesfm#29]
Our code (following the sample)

```
model = timesfm.TimesFm(
    context_len=128,
    horizon_len=5,
    input_patch_len=32,
    output_patch_len=128,
    num_layers=20,
    model_dims=1280,
    backend=backend,
)
model.load_from_checkpoint(repo_id="google/timesfm-1.0-200m")
```

then our process gives the GPU memory usage around **12237MiB**

![image](https://github.com/google-research/timesfm/assets/1491308/aeb42bdd-43dd-4377-b625-6386e3c1b7a4)

**Comment by blackcat1402** [comment]
that is a lot

**Comment by R3xpook** [comment]
I have 64gb of ram and 64 of swap and it oom XD sooooo

**Comment by rajatsen91** [comment]
Can you try setting the environment variable: XLA_PYTHON_CLIENT_PREALLOCATE=false ?
