### ISSUE TITLE
Can we use our private data to train this foundation model ?

### ISSUE THREAD

**Issue by hvacking** [google-research/timesfm#31]
Can we use our private data to train this foundation model ?

**Comment by eric-vader** [comment]
Would be interested too, also to finetune from the pre-trained model.

Some instructions would be great, I can find mostly inference stuff in the code.

**Comment by rajatsen91** [comment]
While this is not the whole pretraining code but a we have provided code to finetune the model here :https://github.com/google-research/timesfm/tree/master/notebooks
