### ISSUE TITLE
Access to model google/timesfm-1.0-200m is restricted

### ISSUE THREAD

**Issue by lanqiuyao** [google-research/timesfm#33]
Hi, I am trying to utilize the package, but got the error for 

```
Cannot access gated repo for url https://huggingface.co/api/models/google/timesfm-1.0-200m/revision/main.
Access to model google/timesfm-1.0-200m is restricted. You must be authenticated to access it.
```

**Comment by sdmorrey** [comment]
@lanqiuyao You need a hugging face account and you need to register your public key with hugging face then you need to agree to google's terms of service on the HF repo page. Once you do that you can git clone the model using ssh.

I recommend you clone it directly and make a backup copy to your own HF account. This will allow you to use the repo="" command but pointed at your own repo.

**Comment by usmanjdn93** [comment]
@lanqiuyao  need to generate the access token in your profile setting then run the below cmd in terminal
`huggingface-cli login`
it will ask to paste the access token. rerun it will work
