### ISSUE TITLE
experimental_quantile_forecast are always the same regardless of different quantiles choices?

### ISSUE THREAD

**Issue by houghtonweihu** [google-research/timesfm#38]
I tried two different quantiles:

    quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.90, 0.95, 0.98, 0.99],

but the experimental_quantile_forecast are always the same.

![image](https://github.com/google-research/timesfm/assets/17937479/7b040297-7615-4546-8a9f-b057502c1d00)

![image](https://github.com/google-research/timesfm/assets/17937479/2e26bc5f-5b71-4344-bd91-7fc234273ae0)

**Comment by sdmorrey** [comment]
If I'm reading the paper correctly the quantile heads need to be fine tuned by the end user. Which makes sense when you stop and think about it, they're the part most likely to be reliant on unseen data.

**Comment by rajatsen91** [comment]
Sorry for the confusion. During pretraining we only train for quantiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]. Therefore at the moment the current checkpoint can only infer those quantiles.
