### ISSUE TITLE
the self._pmapped_decode interrupted, and does not output any errors

### ISSUE THREAD

**Issue by mariomoonetedsfsd** [google-research/timesfm#40]
checkpoint_path is : checkpoints
Constructing model weights.
Constructed model weights in 1.39 seconds.
Restoring checkpoint from checkpoints.
WARNING:absl:No registered CheckpointArgs found for handler type: <class 'paxml.checkpoints.FlaxCheckpointHandler'>
WARNING:absl:Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate by May 1st, 2024.
Restored checkpoint in 1.00 seconds.
Jitting decoding

**Comment by siriuz42** [comment]
Jitting will take a while (e.g. up to 1 minute on my server with 2x Intel Xeon Gold 6154). Any luck if you wait a bit longer?

**Comment by mariomoonetedsfsd** [comment]
checkpoint_path is : checkpoints
Constructing model weights.
Constructed model weights in 1.41 seconds.
Restoring checkpoint from checkpoints.
WARNING:absl:No registered CheckpointArgs found for handler type: <class 'paxml.checkpoints.FlaxCheckpointHandler'>
WARNING:absl:Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate by May 1st, 2024.
Restored checkpoint in 0.90 seconds.
Jitting decoding.

- The above is all my output, without inputting anything after output Jitting decoding. On my computer AMD Ryzen 7 7840H with Radeon 780M Graphics, wsl configured x86_64 Ubuntu
