### ISSUE TITLE
`import timesfm` failed

### ISSUE THREAD

**Issue by heroygt** [google-research/timesfm#42]
`import timesfm
`
Throw an error

`RuntimeError: jaxlib version 0.4.28 is newer than and incompatible with jax version 0.4.26. Please update your jax and[/or](https://noam-jl.nioint.com/or) jaxlib packages.`

**Comment by sdmorrey** [comment]
Don't ya love it when they break everything on a point release?

I had this issue. I eventually discovered it was because I had missed a couple of important steps in the README.

**Comment by rajatsen91** [comment]
I believe this can be fixed by downgrading the jaxlib version to 0.4.26.

**Comment by giusparsifal** [comment]
> I believe this can be fixed by downgrading the jaxlib version to 0.4.26.

I have this error too and I did as you suggested, but still error persist even if it disinstalled 0.4.28...
