### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by forhonourlx** [google-research/timesfm#48]
Try to install timesfm in docker, using 
`conda env create --file=environment.yml`
`conda activate tfm_env`
`pip install -e .`
get:
```
>>> import timesfm
2024-05-22 12:33:11.430855: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
```
Installation is rather difficult, could you offer a docker image or in any certain way?
Thanks inadvance.

**Comment by rajatsen91** [comment]
The model should still run despite this warning.

**Comment by forhonourlx** [comment]
> The model should still run despite this warning.

Despite GPU is not available?

**Comment by jacklee018** [comment]
> The model should still run despite this warning.

When I ran "timesfm.py" in the virtual machine "Ubuntu 18.04.6", the same warning occurred and the process was killed soon after. Have you encountered such a problem or could you introduce your environment and deployment briefly?

**Comment by Treffenovo** [comment]
> > The model should still run despite this warning.
> 
> Despite GPU is not available?

hi, can I ask how you solved this problem, I'm also experiencing this problem
