### ISSUE TITLE
Cannot offset times with data type: 'dbdate'

### ISSUE THREAD

**Issue by gte644q** [google-research/timesfm#50]
I was running the following code 
forecast_df = tfm.forecast_on_df(
    inputs=df,
    freq="D",  # daily
    value_name="y",
    num_jobs=-1,
)
It shows the following message
'Processing dataframe with multiple processes.
Finished preprocessing dataframe.
Finished forecasting.
'
Then failed with this message 
'ValueError: Cannot offset times with data type: 'dbdate' using a frequency of type: '<class 'pandas._libs.tslibs.offsets.Day'>'.'

**Comment by baldwibr** [comment]
Sounds like your 'ds' input is `dbdate` rather than a `datetime64[ns]` format which it expects. Convert the field type prior to running it through `forecast_on_df`.

    df['ds'] = pd.to_datetime(df['ds'])

**Comment by gte644q** [comment]
It turns out that some days are missing values. Once I fixed the missing value, the error is gone now.
