### ISSUE TITLE
The training code

### ISSUE THREAD

**Issue by mickey-cool** [google-research/timesfm#61]
Will you release the training code? That would be great if you will.

**Comment by Marchetz** [comment]
I would also be interested, it would be really useful and interesting to understand better the training part explained in the paper. Thanks!

**Comment by Houyikai** [comment]
same question

**Comment by sh0116** [comment]
same question

**Comment by VmFree** [comment]
me too. especially to understand random number's usage:
`Suppose the maximum context length is 512 and p = 32. Then if r = 4, the output prediction after seeing the ffrst
patch (from o1) is optimized to predict after seeing 28 = 32 − 4 time-points, the output of the next patch (from o2) is
optimized to predict after seeing 28 + 32 time-points, and so on. When this argument is repeated for all such r’s, the
model has seen all possible context lengths till 512.
`

**Comment by rajatsen91** [comment]
While this is not the whole pretraining code but a we have provided code to finetune the model here :https://github.com/google-research/timesfm/tree/master/notebooks
