### ISSUE TITLE
Request for Google Timesfm Training Code Access for Academic Research

### ISSUE THREAD

**Issue by superlin30** [google-research/timesfm#84]
Hello Google Timesfm Team,

I am reaching out to inquire if there is any possibility of obtaining the training code for the Google Timesfm model. Our research team is eager to explore its potential in our field and would greatly benefit from the ability to fine-tune the model for our specific use case.

We believe it would significantly enhance our research efforts. If there is a way to access the training code or any related documentation, we would be very grateful.

**Comment by rajatsen91** [comment]
While this is not the whole pretraining code but a we have provided code to finetune the model here :https://github.com/google-research/timesfm/tree/master/notebooks

**Comment by superlin30** [comment]
您好，这里是西财一枝花，电商王力宏，张林的邮箱，已收到您的邮件
